// <auto-generated />
using System;
using DACS_QuanLyPhongTro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACS_QuanLyPhongTro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChiSoDienNuoc", b =>
                {
                    b.Property<int>("MaChiSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiSo"));

                    b.Property<decimal>("ChiSoDienCu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChiSoDienMoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChiSoNuocCu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChiSoNuocMoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGiaDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DonGiaNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Thang")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChiSo");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiSoDienNuocs");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChiTietHoaDonDichVu", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("DichVuMaDichVu")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoaDonMaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon", "MaDichVu");

                    b.HasIndex("DichVuMaDichVu");

                    b.HasIndex("HoaDonMaHoaDon");

                    b.ToTable("ChiTietHoaDonDichVus");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChiTietPhieuDangKyDichVu", b =>
                {
                    b.Property<int>("MaDangKyDichVu")
                        .HasColumnType("int");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int");

                    b.Property<int>("DichVuMaDichVu")
                        .HasColumnType("int");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaChiTiet")
                        .HasColumnType("int");

                    b.Property<int>("PhieuDangKyDichVuMaDangKyDichVu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDangKyDichVu", "MaDichVu");

                    b.HasIndex("DichVuMaDichVu");

                    b.HasIndex("PhieuDangKyDichVuMaDangKyDichVu");

                    b.ToTable("ChiTietPhieuDangKyDichVus");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChuTro", b =>
                {
                    b.Property<int>("MaChuTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuTro"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChuTro");

                    b.ToTable("ChuTros");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<DateTime>("HanThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KhachThueMaKhachThue")
                        .HasColumnType("int");

                    b.Property<int>("MaChiSo")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachThue")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienDien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienNuoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("KhachThueMaKhachThue");

                    b.HasIndex("MaChiSo");

                    b.HasIndex("MaKhachThue");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHopDong"));

                    b.Property<int>("KhachThueMaKhachThue")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachThue")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHopDong");

                    b.HasIndex("KhachThueMaKhachThue");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.KhachThue", b =>
                {
                    b.Property<int>("MaKhachThue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachThue"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("PhongTroMaPhong")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachThue");

                    b.HasIndex("PhongTroMaPhong");

                    b.ToTable("KhachThues");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhieuDangKyDichVu", b =>
                {
                    b.Property<int>("MaDangKyDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKyDichVu"));

                    b.Property<int>("KhachThueMaKhachThue")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachThue")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDangKyDichVu");

                    b.HasIndex("KhachThueMaKhachThue");

                    b.ToTable("PhieuDangKyDichVus");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhieuGhiNhanSuCo", b =>
                {
                    b.Property<int>("MaSuCo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSuCo"));

                    b.Property<int>("KhachThueMaKhachThue")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachThue")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayGiaiQuyet")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSuCo");

                    b.HasIndex("KhachThueMaKhachThue");

                    b.ToTable("PhieuGhiNhanSuCos");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhieuThanhToan", b =>
                {
                    b.Property<int>("MaPhieuThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuThanhToan"));

                    b.Property<int>("HoaDonMaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaPhuongThuc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhuongThucThanhToanMaPhuongThuc")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuThanhToan");

                    b.HasIndex("HoaDonMaHoaDon");

                    b.HasIndex("PhuongThucThanhToanMaPhuongThuc");

                    b.ToTable("PhieuThanhToans");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhongTro", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<decimal>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaToaNha")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<int>("ToaNhaMaToaNha")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhong");

                    b.HasIndex("ToaNhaMaToaNha");

                    b.ToTable("PhongTros");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("MaPhuongThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhuongThuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhuongThuc");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ToaNha", b =>
                {
                    b.Property<int>("MaToaNha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaToaNha"));

                    b.Property<int>("ChuTroMaChuTro")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaChuTro")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenToaNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongSoTang")
                        .HasColumnType("int");

                    b.HasKey("MaToaNha");

                    b.HasIndex("ChuTroMaChuTro");

                    b.ToTable("ToaNhas");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChiSoDienNuoc", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.PhongTro", "PhongTro")
                        .WithMany("ChiSoDienNuocs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChiTietHoaDonDichVu", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuMaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_QuanLyPhongTro.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDonDichVus")
                        .HasForeignKey("HoaDonMaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChiTietPhieuDangKyDichVu", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.DichVu", "DichVu")
                        .WithMany("ChiTietPhieuDangKyDichVus")
                        .HasForeignKey("DichVuMaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_QuanLyPhongTro.Models.PhieuDangKyDichVu", "PhieuDangKyDichVu")
                        .WithMany("ChiTietPhieuDangKyDichVus")
                        .HasForeignKey("PhieuDangKyDichVuMaDangKyDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("PhieuDangKyDichVu");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.HoaDon", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.KhachThue", null)
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachThueMaKhachThue");

                    b.HasOne("DACS_QuanLyPhongTro.Models.ChiSoDienNuoc", "ChiSoDienNuoc")
                        .WithMany()
                        .HasForeignKey("MaChiSo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DACS_QuanLyPhongTro.Models.KhachThue", "KhachThue")
                        .WithMany()
                        .HasForeignKey("MaKhachThue")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChiSoDienNuoc");

                    b.Navigation("KhachThue");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.HopDong", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.KhachThue", "KhachThue")
                        .WithMany("HopDongs")
                        .HasForeignKey("KhachThueMaKhachThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachThue");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.KhachThue", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.PhongTro", "PhongTro")
                        .WithMany("KhachThues")
                        .HasForeignKey("PhongTroMaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongTro");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhieuDangKyDichVu", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.KhachThue", "KhachThue")
                        .WithMany("PhieuDangKyDichVus")
                        .HasForeignKey("KhachThueMaKhachThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachThue");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhieuGhiNhanSuCo", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.KhachThue", "KhachThue")
                        .WithMany("PhieuGhiNhanSuCos")
                        .HasForeignKey("KhachThueMaKhachThue")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachThue");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhieuThanhToan", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.HoaDon", "HoaDon")
                        .WithMany("PhieuThanhToans")
                        .HasForeignKey("HoaDonMaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS_QuanLyPhongTro.Models.PhuongThucThanhToan", "PhuongThucThanhToan")
                        .WithMany("PhieuThanhToans")
                        .HasForeignKey("PhuongThucThanhToanMaPhuongThuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("PhuongThucThanhToan");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhongTro", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.ToaNha", "ToaNha")
                        .WithMany("PhongTros")
                        .HasForeignKey("ToaNhaMaToaNha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToaNha");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ToaNha", b =>
                {
                    b.HasOne("DACS_QuanLyPhongTro.Models.ChuTro", "ChuTro")
                        .WithMany("ToaNhas")
                        .HasForeignKey("ChuTroMaChuTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuTro");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ChuTro", b =>
                {
                    b.Navigation("ToaNhas");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietPhieuDangKyDichVus");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDonDichVus");

                    b.Navigation("PhieuThanhToans");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.KhachThue", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("HopDongs");

                    b.Navigation("PhieuDangKyDichVus");

                    b.Navigation("PhieuGhiNhanSuCos");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhieuDangKyDichVu", b =>
                {
                    b.Navigation("ChiTietPhieuDangKyDichVus");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhongTro", b =>
                {
                    b.Navigation("ChiSoDienNuocs");

                    b.Navigation("KhachThues");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("PhieuThanhToans");
                });

            modelBuilder.Entity("DACS_QuanLyPhongTro.Models.ToaNha", b =>
                {
                    b.Navigation("PhongTros");
                });
#pragma warning restore 612, 618
        }
    }
}
